[target.thumbv7m-none-eabi]
runner = 'probe-rs run --chip STM32F103ZE'

[target.thumbv7em-none-eabihf]
runner = 'probe-rs run --chip STM32H747XIHx'

[build]
target = "thumbv7m-none-eabi" # Cortex-M3
#target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)

[env]
DEFMT_LOG = "trace"
